version: '3'
services:

### Deprecated ###
#  jupyter:
#    image: avbee/jupynote-spark-pytorch
#    environment:
#       - "JUPYTER_LAB_ENABLE=yes" 
#   # host_command: export UID
#    volumes:
#       - /home/ubuntu/jupyter:/home/jovyan
#    ports:
#       - 8888:8888

#  jenkins:
#    image: jenkins
#    user: root
#    volumes:
#       - /opt/jenkins:/var/jenkins_home
#    ports:
#       - 8081:8080
#       - 50000:50000


#API GATEWAY PACKAGE
  kong-database:
    image: postgres:9.5
    ports:
       - 5432:5432
    environment:
       - "POSTGRES_USER=kong"
       - "POSTGRES_DB=kong"
    volumes:
       - /home/ubuntu/my-postgres.conf:/etc/postgresql/postgresql.conf
       - /var/lib/postgresql/data:/var/lib/postgresql/data
       

    healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:5432"]
       test: ["CMD-SHELL","pg_isready -U postgres"]
       interval: 10s
       timeout: 5s
       retries: 3


#  kong-database:
#    image: cassandra:3
#    ports:
#       - 9042:9042

### Migration should be done manually once ###
#  kong-migration:
#    image: kong:0.13
#    environment:
#       - "KONG_DATABASE=postgres"
#       - "KONG_CASSANDRA_CONTACT_POINTS=kong-database"
#       - "KONG_PG_HOST=kong-database"
#    links:
#       - kong-database:kong-database
#    command: kong migrations up


  thekong:
    image: kong:0.14
    depends_on:
       - kong-database
#       - kong-migration
    restart : unless-stopped
    environment:
       - "KONG_DATABASE=postgres"
       - "KONG_CASSANDRA_CONTACT_POINTS=kong-database"
       - "KONG_PG_HOST=kong-database"
       - "KONG_PROXY_ACCESS_LOG=/dev/stdout"
      - "KONG_PROXY_ERROR_LOG=/dev/stderr"
       - "KONG_ADMIN_ERROR_LOG=/dev/stderr"
       - "KONG_ADMIN_LISTEN=0.0.0.0:8001"
       - "KONG_ADMIN_LISTEN_SSL=0.0.0.0:8444"

#    volumes:
#      - /opt/kong:/etc/kong
    ports:
       - 8000:8000
       - 8443:8443
       - 8001:8001
       - 8444:8444
    links:
       - kong-database:kong-database

  kong-dashboard:
    image: pgbi/kong-dashboard
    environment:
       - "KONG_DATABASE=postgres"
       - "KONG_CASSANDRA_CONTACT_POINTS=kong-database"
       - "KONG_PG_HOST=kong-database"
    ports:
       - 8080:8080
    links:
       - kong-database:kong-database
       - thekong:thekong
    depends_on:
       - kong-database
       - thekong

    command: start --kong-url http://thekong:8001 --basic-auth ntustsc=bmwee809

######API############

  post:
    image: avbee/post
    ports:
      - 8880:8080
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      resources:
        limits:
          #cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
 
  get:
    image: avbee/get
    ports:
      - 8881:8081
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      resources:
        limits:
          #cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M

  weather:
    image: avbee/weather
    restart: unless-stopped

    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      resources:
        limits:
          #cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M

  airboxpost:
    image: avbee/airboxpost:0.9.0
    restart: unless-stopped
    ports:
    - 8890:8090
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

    deploy:
      resources:
        limits:
#          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M


  aggregate:
    image: avbee/agg
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"


  airboxpost:
    image: avbee/airboxpost
    restart: unless-stopped
    ports:
    - 8890:8090
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
       
=======

  airboxpost:
    image: avbee/airboxpost
    restart: unless-stopped

