openapi: 3.0.0
info:
  title: Smart Meter API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://140.118.70.136:9111
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

paths:
  /tests:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user naPmes
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /quarterpost:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user naPmes
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
