# version: '3'
# services:
#   reverse_proxy:
#     image: nginx
#     volumes:
#       - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
#     ports:
#      - "10000:8080"
#      - "10001:8081"
#      - "10002:8082"
#      - "10003:8083"
#      - "10004:8084"
#      - "10005:8085"
#      - "10006:8086"
#      - "10007:8087"


version: '3'
services:
  reverse_proxy:
    image: nginx
    volumes:
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/smartcampus.et.ntust.edu.tw/fullchain.pem:/etc/nginx/fullchain.pem
      - /etc/letsencrypt/live/smartcampus.et.ntust.edu.tw/privkey.pem:/etc/nginx/privkey.pem
      - /etc/letsencrypt/live/smartcampus.et.ntust.edu.tw/chain.pem:/etc/nginx/chain.pem
      - /etc/ssl/certs/dhparams.pem:/etc/nginx/dhparams.pem
    ports:
     - "10000:8080"
     - "10001:8081"
     - "10002:8082"
     - "10003:8083"
     - "10004:8084"
     - "10005:8085"
     - "10006:8086"
     - "10007:10007"
     - "11045:11045"
     - "10008:10008"
     - "10009:10009"
     - "443:443"
     - "80:80"
     - "5417:5417"
     - "5420:5420"
#     - "3000:3000"
#  prom:
#    image: prom/prometheus
#    ports:
#     - 9100:9100
#     - 9090:9090
#  node-exporter:
#    image: prom/node-exporter
#    links:
#     - prom:prom
