mongodb:
    host: 127.0.0.1
    port: 20071
    user: peter
    pass: 111111

sql:
    host : 172.0.0.1
    port: 3306
    user: peter
    pass: 2222222

elastic:
    host: 127.0.0.1
    port: 9002

redis:
    host: 127.0.0.1:6379
    pass: ""
    db: 0

log:
    path: /var/log
    duration: hour   # day - hour - minute
    debug: true      # false(關閉) | true(開啟)

api:
    port: 9080
    allowedHeaders: 
        - Content-Type 
        - system
        - token
    allowedMethods:
        - GET
        - POST
        - PUT
    allowedOrigins:
        - "*"
