FROM scratch
MAINTAINER Fransiscus Bimo <avbee.lab@gmail.com>
ENV MONGO_URL "172.16.0.132:27017"
ENV USERNAME "dontask"
ENV PASS "idontknow"
ENV DB_AUTH "admin"
ADD airboxget /
ENTRYPOINT ["/airboxget"]
#CMD ./post
