version: '3.7'

services:

  mongo:
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - /data/db:/data/db
    environment:
     # - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=dontask
      - MONGO_INITDB_ROOT_PASSWORD=idontknow


  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: dontask
      ME_CONFIG_MONGODB_ADMINPASSWORD: idontknow
      ME_CONFIG_BASICAUTH_USERNAME: bmwiot
      ME_CONFIG_BASICAUTH_PASSWORD: bmwee809
