# api:
#   interval: 60s
#   uri: "http://requestb.in/13gerls1"
#   key: "48593282-b38d-4bf5-af58-f7327271e73d"
#   pid: "something-static"
nodes:
  sourcemongo:
    type: mongo
    uri: mongodb://root:123@140.118.70.136:27017/Bimo_test?authSource=admin
    #namespace: Bimo_test.SC01_displayData_All
  es:
    type: elasticsearch
    uri: http://localhost:9200/
    namespace: index.device_All
  # timeseries:
  #   type: influx
  #   uri: influxdb://root:root@localhost:8086/compose
  # debug:
  #   type: file
  #   uri: stdout://
  # foofile:
  #   type: file
  #   uri: file:///tmp/foo
