# This is a comment
FROM golang:1.9
MAINTAINER Docker Peter <ch.focke@gmail.com>

RUN go get github.com/gorilla/mux
RUN go get github.com/lestrrat/go-file-rotatelogs
RUN go get gopkg.in/olivere/elastic.v5
RUN go get gopkg.in/mgo.v2
RUN go get gopkg.in/yaml.v2
RUN go get github.com/denisenkom/go-mssqldb
RUN go get github.com/RichardKnop/machinery/v1
RUN go get googlemaps.github.io/maps
RUN go get github.com/go-redis/redis
RUN go get github.com/tealeg/xlsx
RUN go get github.com/betacraft/yaag/yaag
RUN go get github.com/betacraft/yaag/middleware
RUN go get github.com/SebastiaanKlippert/go-wkhtmltopdf
RUN go get github.com/go-sql-driver/mysql
RUN go get github.com/gorilla/handlers
RUN go get github.com/asaskevich/govalidator
RUN go get github.com/stretchr/testify/assert
RUN go get github.com/robfig/cron